apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: b
  name: b
  annotations:
    'consul.hashicorp.com/connect-inject': 'true'
    'consul.hashicorp.com/connect-service-upstreams': 'nginx:80'
spec:
  containers:
  - image: busybox
    name: b
    command:
      - /bin/sh
      - -c
      - 'while true; do sleep 10000; done'
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
