# Choose an optional name for the datacenter
global:
  datacenter: minidc

# Enable the Consul Web UI via a NodePort
ui:
  service:
    type: 'NodePort'

# Enable Connect for secure communication between nodes
connectInject:
  enabled: true
# Enable CRD controller
controller:
  enabled: true

client:
  enabled: true

# Use only one Consul server for local development
server:
  replicas: 3
  bootstrapExpect: 3
  storage: 1Gi
  storageClass: openebs-hostpath
  disruptionBudget:
    enabled: true
    maxUnavailable: 0

syncCatalog:
  enabled: true

