apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: http-mesh
    app: http-mesh
  name: httpd-mesh
  annotations:
    'consul.hashicorp.com/connect-inject': 'true'
spec:
  volumes:
    - name: share-vol
      emptyDir: {}
  initContainers:
  - name: init-pod
    image: busybox
    volumeMounts:
      - name: share-vol
        mountPath: /output
    command:
      - sh
      - -c
      - 'echo init container-hostname \: $HOSTNAME >> /output/index.html'
  containers:
  - image: nginx:1.19.6
    name: nginx
    env:
      - name: NGINX_PORT
        value: "80"
    ports:
      - containerPort: 80
    volumeMounts:
      - name: share-vol
        mountPath: /usr/share/nginx/html
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
